repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            files: (src/antio|tests)

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.6
      hooks:
          - id: ruff
            name: ruff linter
            args: [--fix, --show-fixes]
            files: (src/antio|tests)
          - id: ruff-format
            name: ruff formatter
            files: (src/antio|tests)

    - repo: https://github.com/codespell-project/codespell
      rev: v2.3.0
      hooks:
          - id: codespell
            args: [--write-changes]
            additional_dependencies: [tomli]
            files: (src/antio|tests)

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            files: (src/antio|tests)
            additional_dependencies: [tomli]

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.23.1
      hooks:
          - id: toml-sort-fix
            files: pyproject.toml

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|.codecov.yaml|.pre-commit-config.yaml|.yamllint.yaml)
