name: cibuildwheel
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build-libeep-linux:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: libeep ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: libeep
          path: src
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ./src
          cmake --build . --config Release
          mv python/v3/pyeep.so ./pyeep.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libeep-${{ matrix.os }}
          path: |
            ./libEep.so
            ./pyeep.so

  build-libeep-windows:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    name: libeep - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: libeep
          path: src
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ./src
          cmake --build . --config Release
          mv ./Release/Eep.dll ./Eep.dll
          mv ./python/v3/Release/pyeep.pyd ./pyeep.pyd
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libeep-${{ matrix.os }}
          path: |
            ./Eep.dll
            ./pyeep.pyd

  build-libeep-macos:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13]
    name: libeep - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: libeep
          path: src
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ./src
          cmake --build . --config Release
          mv ./python/v3/pyeep.so ./pyeep.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libeep-${{ matrix.os }}
          path: |
            ./libEep.dylib
            ./pyeep.so

  build_wheels:
    needs: [build-libeep-linux, build-libeep-windows, build-libeep-macos]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: src
      - name: Retrieve libeep
        uses: actions/download-artifact@v4.1.8
        with:
          name: libeep-${{ matrix.os }}
          path: ./src/antio/libeep/
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        with:
            package-dir: ./src
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
